### ISSUE TITLE
Predecessor lists inconsistencies

### ISSUE THREAD

**Issue by ljwolf** [pysal/pysal#576] opened 2015-02-18 21:09 UTC
![screen shot 2015-02-18 at 1 40 29 pm](https://cloud.githubusercontent.com/assets/2250995/6256280/0781d954-b774-11e4-8d3b-ca56425df97b.png)

See attached screenshot. `IN[4]` is the predecessor path for 0 to 3, and `IN[5]` is the predecessor path for 229 to 215. After poking around further, it looks like the predecessor path is inconsistent. Sometimes,  it ends at the starting node but other times it ends right before the starting node.

I stumbled upon this while trying to format the output of a floyd-warshall all-pairs shortest path algorithm ([gist](https://gist.github.com/ljwolf/ceafdd7a6c26d9f2c4f9)) to match the output of the current implementation. The two implementations have the same distances, verified using `numpy.testing.assert_array_almost_equal()` on the two distance matrices, but the predecessor graphs were failing due to the screenshot. Any ideas on this?

**Comment by sjsrey** [comment] 2015-02-20 23:46
We are also missing at least one path:

![screenshot 2015-02-20 16 45 14](https://cloud.githubusercontent.com/assets/118042/6311439/045954a2-b920-11e4-9290-3ccdd873b8d3.png)

**Comment by sjsrey** [comment] 2015-02-21 00:02
We are missing a lot of paths
![screenshot 2015-02-20 17 01 20](https://cloud.githubusercontent.com/assets/118042/6311593/2ce04a96-b922-11e4-8ff6-645ecf295361.png)

**Comment by jlaura** [comment] 2015-02-21 00:09
I'll give this a look around 7pm. The functions should have been failing in
the areas where this many paths were missing.

**Comment by jlaura** [comment] 2015-02-21 02:46
Looks like I screwed up an iterator inside of the generatetree function (ps.network.utils).  Working on the fix now and will get the sleuth work turned into a few unit tests.

**Comment by jlaura** [comment] 2015-02-21 03:40
The fix is in a PR, but the PR is cluttered with a number of earlier commits.  Has anyone had success deleting a branch, remaking the branch, fetching from upstream, then forcing a push back into their fork?  Basically, want to replace my local network branch with the current ps network branch.

P.S. The above comment was the cause of this - I was using the previous node as the key in the previous dict, which was insanely bad.  The new notebook has what should be a test to ensure that all previous lists (1) have entries for all other nodes and (2) all paths terminate back at the root node.

**Comment by sjsrey** [comment] 2015-02-21 04:03
I think a solution would be

1 rename your local branch (for safe keeping)
2 make sure your local master matches upstream master
3 fetch the upstream network branch
4 add your fix to 3
5 pr on 4

**Closed** 2015-02-27 21:22 UTC
Labels: bug, network
