### ISSUE TITLE
find_bin does not include top value

### ISSUE THREAD

**Issue by jzf2101** [pysal/pysal#968] opened 2017-08-03 12:41 UTC
- Platform information:
posix darwin

- Python version: 
3.6.2 | packaged by conda-forge | (default, Jul 23 2017, 23:01:38) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

- SciPy version:
0.19.1

- NumPy version:
1.13.1

Example classifier:

```
             Fisher_Jenks             
 
Lower          Upper             Count
======================================
        x[i] <= 1.000               5
1.000 < x[i] <= 2.000                2
2.000 < x[i] <= 3.000                3
3.000 < x[i] <= 4.000                4
4.000 < x[i] <= 5.000                4
```

However,

https://github.com/pysal/pysal/blob/master/pysal/esda/mapclassify.py#L765

Doesn't include top number in when I assign the bins.

It's causing errors in my value assignments 

https://docs.scipy.org/doc/numpy/reference/generated/numpy.digitize.html gives me better results

**Comment by sjsrey** [comment] 2017-08-03 14:57
Thanks for reporting this.

So that we can try to help you better, would it be possible to include a small example that reproduces the behavior you are seeing?

From your description, it seems as if you already have the bins for the classes, in which case you wouldn't want to use Fisher_Jenks, but rather use [User_Defined](http://pysal.readthedocs.io/en/latest/library/esda/mapclassify.html#pysal.esda.mapclassify.User_Defined) and pass in your bins as an option.

**Comment by ljwolf** [comment] 2017-08-03 15:26
```python
>>> import pysal as ps
>>> import numpy as np

>>> ud = ps.User_Defined(np.arange(20), [5,10,15])
>>> ud

              User Defined             
 
Lower            Upper            Count
=======================================
         x[i] <=  5.000               6
 5.000 < x[i] <= 10.000               5
10.000 < x[i] <= 15.000               5
15.000 < x[i] <= 19.000               4

>>> ud.find_bin(5) # returns 1
1

**Comment by ljwolf** [comment] 2017-08-03 15:27
`find_bin` treats the upper bound as strictly `<` and the lower as `<=`. this is not what's in the repr, and so it should probably get changed.

**Comment by ljwolf** [comment] 2017-08-03 15:29
For reference, `np.digitize` isn't suitable here, I think, cause it supplies the `k+1`th bin when you're above the classifier, but keeps you at `0` when below the classifier. `find_bin` always supplies the nearest bin in the available data rather than supplying more indices than there are bins.

**Comment by sjsrey** [comment] 2017-08-03 15:45
I think we should change `find_bin` to be consistent with the [original classifier](https://github.com/pysal/pysal/blob/master/pysal/esda/mapclassify.py#L395) which uses half-closed intervals (open on the lower endpoint, closed on the upper endpoint).

**Comment by ljwolf** [comment] 2017-08-03 15:50
yep! PR to [pysal/mapclassify](https://github.com/pysal/mapclassfiy) incoming. The mismatch is definitely not intended behavior. 

I've also updated the docstring to explain the difference between `find_bin` and `np.digitize(x, classi.bins, right=True)`.

**Comment by jzf2101** [comment] 2017-08-03 15:57
@ljwolf yes i meant using `right=True`

**Comment by ljwolf** [comment] 2017-08-03 16:28
Sweet. @jzf2101 the change is now merged upstream. Thank you for the report!

**Closed** 2017-08-03 16:29 UTC

**Comment by ljwolf** [comment] 2017-08-03 16:35
A temporary fix might be to use digitize if you're sure values aren't outside the range of the classifier. 

Another would be something like this:

```python
def find_bin(x,bins=classi.bins):
    right = numpy.digitize(x, bins, right=True)
    if right.max() == len(bins):
        right[right == len(bins)] = len(bins)-1 # decrement the over-bin if present
    return right
```

**Comment by jzf2101** [comment] 2017-08-03 21:29
I would suspect digitize may be faster?

**Comment by ljwolf** [comment] 2017-08-03 21:35
yep, the `find_bin` implementation above using digitize+masked reassignment is ~2ms per eval & the one currently in esda using list comps is ~400ms for finding the bin of 100k points.

**Comment by jzf2101** [comment] 2017-08-04 01:42
could you please update the pr?

**Comment by ljwolf** [comment] 2017-08-04 02:02
No prob. I planned to fix it up later tonight. Thanks for the prompt :)
