### ISSUE TITLE
network ring bug

### ISSUE THREAD

**Issue by dfolch** [pysal/pysal#655] opened 2015-07-09 16:54 UTC
In the case of a ring road with no intersections, the Network builder fails.  The traceback is not informative to the user.  This is a rare case, so is a low priority.

<img width="717" alt="code" src="https://cloud.githubusercontent.com/assets/1322332/8601256/fee9f2a2-2638-11e5-8038-57188a4328d1.png">

<img width="386" alt="ring_road" src="https://cloud.githubusercontent.com/assets/1322332/8601202/a98c9936-2638-11e5-8e89-5b9f4530cf17.png">

**Comment by dfolch** [comment] 2016-02-27 14:23
Here is the troublemaker shapefile. [unconnected_ring.zip](https://github.com/pysal/pysal/files/149357/unconnected_ring.zip)

**Comment by chiragvartak** [comment] 2016-02-27 16:26
The above mentioned shapefile is not the only one that causes problems. I managed to reproduce the error in at least the files `Polygon.shp` and `10740.shp`. (Figure below). There might be more.  
I found another recurring error: `'Point' object has no attribute 'vertices'`, when I tried to create a Network with the shapefiles: `baltim.shp`, `burkitt.shp`, `crimes.shp`, `schools,shp`, `juvenile.shp`. Again, there might be more. (Should I create a new issue regarding this?)  
Also, I feel it would be great to have a method that would give us a list-of-all-files-with-a-specified-extension, given a list-of-names-of-folders in pysal/examples. Something like:
`pysal.examples.get_files(L=['10740', 'geodanet'], ext='shp')`
which would then return:
`['10740.shp', 'crimes.shp', 'schools.shp', 'streets.shp']`
Thus, doing `pysal.examples.get_files(L=pysal.examples.available(), ext='shp')` would give us all the shapefiles and thus testing a function on all of them could be easily done!
(So, create a new issue regarding this too?)  
Thoughts, anyone?  
![network_error](https://cloud.githubusercontent.com/assets/9763219/13373956/600b2702-dd9c-11e5-866a-93d75430fa00.png)

**Comment by sjsrey** [comment] 2016-02-27 17:37
I think the idea of getting a listing of files by type is an interesting one - maybe creating a separate issue from the network thread here would be a good way to start. We could then flesh out the ideas more fully under that issue.

**Comment by sjsrey** [comment] 2016-02-27 17:48
@chiragvartak the extraction of the network works on a polyline shape file, while a points shape file is then used to snap the points onto the network.

We probably should be more explicit in the argument types as currently the [signature](https://github.com/pysal/pysal/blob/master/pysal/network/network.py#L24) is vague on the shapefile type.

**Comment by chiragvartak** [comment] 2016-02-28 12:47
The docstring of `extractgraph` says:
 > Using the existing network representation, create a graph based representation, by removing all nodes with neighbor incidence of two.

What is the reason behind doing this? Why aren't we representing the shapefile as a graph as it is?

**Comment by ljwolf** [comment] 2016-02-28 14:16
When using a polyline shapefile as a network, sometimes you can remove some nodes without changing the resulting topology. I think the original implementor, @jlaura, saw it'd be helpful to keep both the raw polyline set read in from the file, as well as a simplified representation with the same topology. 

Also, just to be clear, the errors you're noticing in constructing a network from something like `baltim.shp' is because 'baltim.shp' does not describe a network. Neither doss 'Polygon.shp,'  but there's probably some more graceful way we could bail out in these cases.

**Comment by jlaura** [comment] 2016-02-29 19:24
@ljwolf is correct that this is going to be a question of storing not just a single representation (potentially).  

For example, assume that we read in the raw polyline shapefile and convert to a networkx style graph.  This is no longer a road network representation, but a reduced topological representation.  That might be great for things like djikstras due to performance (assuming that the true distance is attributed to the topological edge).  What about doing point snapping and edge counts?  The original shapefile is one potential representation, as is the topological representation, as are a myriad of other representations (equal edge segmentation / aggregation over the original shapefile to attempt to standardize edge lengths for example).

In relation to #746, the issue is going to be how to manage different representations of the network and maybe guess at the appropriate realization to use for a given metric.

**Comment by jlaura** [comment] 2016-03-01 17:50
What about pre-processing the full topology to identify cycles.  Then apply
the remove the incidence two logic to the non-cycles.

Question: Should a ring be reduced to a point given the current logic?

**Comment by chiragvartak** [comment] 2016-03-01 20:38
@jlaura With the current logic, the cycle is supposed to be reduced to nothing. But it doesn't happen.  
So, I fixed it and the modified code applies the following logic: A cycle is ignored (actually, it is processed and reduced to nothing) and the other non-cycles are processed properly. I guess this should be alright?

**Comment by dfolch** [comment] 2016-03-01 23:42
I don't think an isolated ring should be removed entirely. Similarly, I don't think an isolated line should be removed either. We might consider a point (@jlaura) or a triangle.  A triangle has the least number of vertices of something looking like a ring.  In the north of the Waverly data ([Waverly.zip](https://github.com/pysal/pysal/files/153801/Waverly.zip)) is a self intersecting road. I think the loop part of this gets reduced to a point under the current code in master.

**Comment by jlaura** [comment] 2016-03-02 02:19
@dfolch Agreed that removal is not appropriate.  The question is, what is appropriate.  I could see an argument for a point, line, or triangle.  Do we have any references how this is handled in the literature?

**Comment by jGaboardi** [comment] 2016-03-02 17:37
@dfolch @ljwolf @jlaura @chiragvartak 
Here is a gist notebook describing and demonstrating the 'loop road' issue.
[Millstream Road](https://gist.github.com/jGaboardi/bab1b0e76429187e6f94)

**Comment by jGaboardi** [comment] 2016-03-02 18:51
[Waverly.zip](https://github.com/pysal/pysal/files/155413/Waverly.zip)

**Comment by jGaboardi** [comment] 2018-12-04 04:39
This issue is resolved with pysal/spaghetti#185. For a demonstration of the new functionality with `unconnected_ring.shp` see [`resolved-unconnected_ring.ipynb`](https://gist.github.com/jGaboardi/3ce1e7b0fb31b8bb169c8a476b1ceec1).

**Closed by jGaboardi** 2018-12-04 04:39 UTC
Labels: Bug, Network
