### ISSUE TITLE
`ps.threshold_continuousW_from_shapefile` returning inf along diagonal

### ISSUE THREAD

**Issue by darribas** [pysal/pysal#800] opened 2016-04-28 03:45 UTC
Here's an example of the problem using Columbus data:

```python
shp_link = ps.examples.get_path('columbus.shp')

thr = ps.min_threshold_dist_from_shapefile(shp_link)

w = ps.threshold_continuousW_from_shapefile(shp_link, thr)
```

If I now do:

```python
w.full()[0].diagonal()
```

I get:

```shell
array([ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf,  inf,  inf,  inf])
```

This is important because it trickles down to computations involving the lag. For example:

```python
dbf = ps.open(shp_link.replace('.shp', '.dbf'))
y = dbf.by_col_array('INC')
mi = ps.Moran(y, wt_distance)
```

Then returns:

```python
>>> mi.I
nan
```

**Comment by darribas** [comment] 2016-04-28 03:46
@dfolch Would this have to do with the changes we introduce relating to kernel weights Vs standard weights? As a default, I think this is not an intuitive one.

**Comment by sjsrey** [comment] 2016-04-28 04:29
@darribas I am seeing:
```
>>> shp_link = ps.examples.get_path('columbus.shp')
>>> thr = ps.min_threshold_dist_from_shapefile(shp_link)
>>> thr
0.61886415807685413
>>> w = ps.threshold_continuousW_from_shapefile(shp_link, thr)
>>> w.full()[0].diagonal()
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
>>>
```

**Comment by ljwolf** [comment] 2016-04-28 05:25
I think this is a duplicate of the self-neighbor bug?  #779, right? 

@darribas, `assert ps.verion == 1.11.1`?

**Comment by darribas** [comment] 2016-04-28 13:10
Ahh I was using 1.11.0. I confirm that upgrading to 1.11.1 solves the problem.

**Closed** 2016-04-28 13:10 UTC
Labels: bug
