### ISSUE TITLE
dbf2df can not read dbf files within which there are Chinese characters

### ISSUE THREAD

**Issue by frenet** [pysal/pysal#849] opened 2016-07-21 16:55 UTC
from pyGDsandbox.dataIO import df2dbf, dbf2df

df=dbf2df('readable.dbf')

print df

try:
    df2=dbf2df('unreadable.dbf')
except:
    print 'unreadable, error happened, because of Chinese words in the unreadable.dbf file'
    print "How can I read all the content within the DBF files?"

df2=dbf2df('unreadable.dbf')
    
if __name__ == '__main__':
    pass

the following is the results:

    df2=dbf2df('unreadable.dbf')
  File "F:\Py4ArcGIS\test_dbf2df\pyGDsandbox\dataIO.py", line 89, in dbf2df
    data = dict([(var, db.by_col(var)) for var in vars_to_read])
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\pysal\core\Tables.py", line 25, in __call__
    return self.p._get_col(key)
  File "C:\Python27\ArcGISx6410.3\lib\site-packages\pysal\core\IOHandlers\pyDbfIO.py", line 120, in _get_col
    value = value.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)

**Comment by ljwolf** [comment] 2016-07-21 17:27
Can you provide some replication data (or just a dbf with Chinese characters)? 

Also, did this occur after you updated pysal? Or, is this the first time you've tried?

**Comment by frenet** [comment] 2016-07-22 01:40
I'm using pysal 1.11.2 which is installed by the command "pip install pysal". 
I've tried to upload the dbf file in a ZIP file but unfortunately failed many times.

**Comment by frenet** [comment] 2016-07-22 04:27
When I tried dbfpy from the following website, it works for the unreadable dbf file. 
Since it is inconvenient to  convert a dbf file into a pandas dataframe by use of dbfpy, I still look forward to have a function which can read the dbf file directly into a pandas dataframe.


#https://pypi.python.org/pypi/dbfpy/2.3.1
from dbfpy import dbf
un=dbf.Dbf('unreadable.dbf')

un.header
Version (signature): 0x03
        Last update: 2016-07-22
      Header length: 993
      Record length: 572
       Record count: 12
 FieldName Type Len Dec
      NAME    C  30   0
     INDEX    N   9   0
     CODDN    F  19  11
     SO2DN    F  19  11
     LU1DN    F  19  11
     LU2DN    F  19  11
     LU3DN    F  19  11
     LU4DN    F  19  11
     LU5DN    F  19  11
     LU6DN    F  19  11
    FERTDN    F  19  11
   PESTIDN    F  19  11
    MEATDN    F  19  11
   POPYEDN    F  19  11
    GDP1DN    F  19  11
    GDP2DN    F  19  11
    GDP3DN    F  19  11
  FIXINVDN    F  19  11
    BIOMDN    F  19  11
    TPOPDN    F  19  11
   URPOPDN    F  19  11
   RUPOPDN    F  19  11
     HHSDN    F  19  11
    ROADDN    F  19  11
LU1PERCENT    F  19  11
LU2PERCENT    F  19  11
LU3PERCENT    F  19  11
LU4PERCENT    F  19  11
LU5PERCENT    F  19  11
LU6PERCENT    F  19  11
un.fieldNames
['NAME', 'INDEX', 'CODDN', 'SO2DN', 'LU1DN', 'LU2DN', 'LU3DN', 'LU4DN', 'LU5DN', 'LU6DN', 'FERTDN', 'PESTIDN', 'MEATDN', 'POPYEDN', 'GDP1DN', 'GDP2DN', 'GDP3DN', 'FIXINVDN', 'BIOMDN', 'TPOPDN', 'URPOPDN', 'RUPOPDN', 'HHSDN', 'ROADDN', 'LU1PERCENT', 'LU2PERCENT', 'LU3PERCENT', 'LU4PERCENT', 'LU5PERCENT', 'LU6PERCENT'] 

un[1]
<xml><more>False</more><output message="      NAME: 嘉荫县 (&lt;type 'str'&gt;)"></output><output message="     INDEX: 1 (&lt;type 'int'&gt;)"></output><output message="     CODDN: 0.205295058851 (&lt;type 'float'&gt;)"></output><output message="     SO2DN: 0.102627935242 (&lt;type 'float'&gt;)"></output><output message="     LU1DN: 0.740998925933 (&lt;type 'float'&gt;)"></output><output message="     LU2DN: 0.0286704883172 (&lt;type 'float'&gt;)"></output><output message="     LU3DN: 0.0920309745027 (&lt;type 'float'&gt;)"></output><output message="     LU4DN: 0.121784958658 (&lt;type 'float'&gt;)"></output><output message="     LU5DN: 0.00648641724822 (&lt;type 'float'&gt;)"></output><output message="     LU6DN: 0.0024026953632 (&lt;type 'float'&gt;)"></output><output message="    FERTDN: 1.23299982377 (&lt;type 'float'&gt;)"></output><output message="   PESTIDN: 0.0389677940726 (&lt;type 'float'&gt;)"></output><output message="    MEATDN: 0.849203814224 (&lt;type 'float'&gt;)"></output><output message="   POPYEDN: 0.00102933795663 (&lt;type 'float'&gt;)"></output><output message="    GDP1DN: 16.2650101976 (&lt;type 'float'&gt;)"></output><output message="    GDP2DN: 5.77679166091 (&lt;type 'float'&gt;)"></output><output message="    GDP3DN: 5.94266212021 (&lt;type 'float'&gt;)"></output><output message="  FIXINVDN: 19.5094834369 (&lt;type 'float'&gt;)"></output><output message="    BIOMDN: 5567247.8626 (&lt;type 'float'&gt;)"></output><output message="    TPOPDN: 10.0844239612 (&lt;type 'float'&gt;)"></output><output message="   URPOPDN: 5.17962859779 (&lt;type 'float'&gt;)"></output><output message="   RUPOPDN: 4.90479536336 (&lt;type 'float'&gt;)"></output><output message="     HHSDN: 3.79266922536 (&lt;type 'float'&gt;)"></output><output message="    ROADDN: 0.000308586696502 (&lt;type 'float'&gt;)"></output><output message="LU1PERCENT: 74.0998925933 (&lt;type 'float'&gt;)"></output><output message="LU2PERCENT: 2.86704883172 (&lt;type 'float'&gt;)"></output><output message="LU3PERCENT: 9.20309745027 (&lt;type 'float'&gt;)"></output><output message="LU4PERCENT: 12.1784958658 (&lt;type 'float'&gt;)"></output><output message="LU5PERCENT: 0.648641724822 (&lt;type 'float'&gt;)"></output><output message="LU6PERCENT: 0.24026953632 (&lt;type 'float'&gt;)"></output></xml>
print un[1][0]
<xml><more>False</more><output message="嘉荫县"></output></xml

**Comment by ljwolf** [comment] 2016-07-22 06:30
I'm glad you found something that works! We should probably keep this issue open until there's a patch or a support decision,  as the encoding is still assumed to be ascii. 

This looks like an issue with python 2/3 string/bytes handling. Since we don't currently support passing an encoding argument to the parser, we implicitly restrict encodings to the default used in bytes.decode.

An easy fix to the code appears in reach: allow a user-specified encoding argument in both reading and writing. This would be a pretty cut and dry contribution!

**Comment by frenet** [comment] 2016-07-24 11:19
Thank you very much.

**Comment by gparadis** [comment] 2016-09-14 03:12
I encountered the exact same issue from `pysal\core\IOHandlers\pyDbfIO.py`. My DBF file is encoded with a silly `cp863` encoding (French Canadian). I had implemented a bit of a monkey-patch solution to decode data _after_ reading it using using pysal, then stuffing the data into a `pandas.DataFrame`:

```
 def read_dbf(dbf_path, index=None, cols=False, codec=None):
    import codecs
    db = ps.open(dbf_path)
    if cols:
        if incl_index:
            cols.append(index)
        vars_to_read = cols
    else:
        vars_to_read = db.header
    data = {}
    for var in vars_to_read:
        if db.field_spec[db.header.index(var)][0] == 'C' and codec:
            data[var.lower()] = map(lambda s: s.decode(codec), db.by_col(var)) 
        else:
            data[var.lower()] = db.by_col(var)
    db.close()
    df = pd.DataFrame(data)
    if index: df = df.set_index(index)
    return df
```

This worked fine in pysal 1.10.0.

Today I had to reinstall pysal, and pip installed pysal 1.11.2. My code broke on line 120 of `pyDbfIO.py`. I compared implementation of `_get_col` on between 1.10.0 and 1.11.2, and the line with `value = value.decode()` is new. This is a backwards-incompatible change, for anyone using non-ASCII encode DBF files.

It would be relatively easy to implement an optional encoding argument to the functions where you added new `decode()` statements (or add a runtime-settable module-level `default_encoding` attribute). This would not change default behavior, but would allow some recourse for users to patch their code with a new encoding argument after a pysal upgrade breaks their existing codebase. The standard Python `decode` function takes an encoding argument, so not much overhead there.

I am building a prototype system right now, and am currently the only user, so I will just downgrade to pysal 1.10.0, put a note in my source code, and keep on truckin', but it would be nice to be able to implement something more robust at my end.

**Comment by ljwolf** [comment] 2016-09-14 03:39
Thanks for this recommendation!
This was a change to the file read/write for interchangeability between 2 and 3 that slipped through testing, since none of our example datasets have non-UTF-8 encodings. 

You're right, it should be possible to just add:
```python
class DBF(pysal.core.Tables.DataTable):

    def __init__(self, *args, **kwargs):
    ...
    self.encoding = kwargs.get('encoding', 'utf8')
```
and then every `encode()`/`decode()` call becomes `encode(self.encoding)`/`decode(self.encoding)`. 
If you have any example replication data on which this fails, it may be easier to test this fix.

Alternatively, you could use geopandas or fiona for your IO, which are dedicated IO packages for geographic data. Almost all of the analytics in pysal are agnostic to the data reader/writer.

**Comment by gparadis** [comment] 2016-09-14 05:14
Glad to help, @ljwolf. Unfortunately, all my examples of real DBF data files that break pysal 1.11.2 technically confidential, so I cannot share my data files with you. Sorry about that.

**Comment by sjsrey** [comment] 2016-09-26 03:59
We are closing this since we can't reproduce.

**Closed by sjsrey** 2016-09-26 03:59 UTC
