### ISSUE TITLE
Dtype error when training the GM Lag model

### ISSUE THREAD

**Issue by rekavonnak** [pysal/pysal#1173] opened 2020-04-21 11:14 UTC
Hello,

I'm trying to run a GM_lag model but I keep getting this error. The input values (a float64 numpy array) that I use work without errors with the OLS base model.
Not sure why this is, seems like a dtype mismatch somewhere. (My pysal version is 1.14.3.)

```
~/opt/anaconda3/lib/python3.7/site-packages/pysal/spreg/twosls_sp.py in __init__(self, y, x, yend, q, w, w_lags, lag_q, robust, gwk, sig2n_k, spat_diag, vm, name_y, name_x, name_yend, name_q, name_w, name_gwk, name_ds)
    495         self.name_w = USER.set_name_w(name_w, w)
    496         self.name_gwk = USER.set_name_w(name_gwk, gwk)
--> 497         SUMMARY.GM_Lag(reg=self, w=w, vm=vm, spat_diag=spat_diag)
    498 
    499 

~/opt/anaconda3/lib/python3.7/site-packages/pysal/spreg/summary_output.py in GM_Lag(reg, vm, w, spat_diag, regimes)
    152     reg.__summary = {}
    153     # compute diagnostics and organize summary output
--> 154     beta_diag_lag(reg, reg.robust, error=False)
    155     if spat_diag:
    156         # compute diagnostics and organize summary output

~/opt/anaconda3/lib/python3.7/site-packages/pysal/spreg/summary_output.py in beta_diag_lag(reg, robust, error)
    719     reg.std_err = diagnostics.se_betas(reg)
    720     reg.z_stat = diagnostics.t_stat(reg, z_stat=True)
--> 721     reg.pr2 = diagnostics_tsls.pr2_aspatial(reg)
    722     # organize summary output
    723     reg.__summary['summary_std_err'] = robust

~/opt/anaconda3/lib/python3.7/site-packages/pysal/spreg/diagnostics_tsls.py in pr2_aspatial(tslsreg)
    213     y = tslsreg.y
    214     predy = tslsreg.predy
--> 215     pr = pearsonr(y, predy)[0]
    216     pr2_result = float(pr ** 2)
    217     return pr2_result

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py in pearsonr(x, y)
   3517         return dtype(np.sign(x[1] - x[0])*np.sign(y[1] - y[0])), 1.0
   3518 
-> 3519     xmean = x.mean(dtype=dtype)
   3520     ymean = y.mean(dtype=dtype)
   3521 

~/opt/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    149             is_float16_result = True
    150 
--> 151     ret = umr_sum(arr, axis, dtype, out, keepdims)
    152     if isinstance(ret, mu.ndarray):
    153         ret = um.true_divide(

TypeError: No loop matching the specified signature and casting was found for ufunc add
```

Let me know if any more info on the environment or the stack trace would be helpful!

Thanks,
Reka

**Comment by ljwolf** [comment] 2020-04-21 11:53
Thanks. I believe this is a duplicate of pysal/spreg#33. The issue actually has to do with a change in `scipy.stats` & how arrays should be shaped. 

To resolve, please use the spreg package directly, which is available on PyPI.

**Closed** 2020-04-21 12:53 UTC

**Comment by rekavonnak** [comment] 2020-04-22 09:40
Thanks, it works now! I didn't realise the issue came up before.
